apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-envoy
  namespace: observability
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - staging

  selector:
    matchLabels:
      security.istio.io/tlsMode: istio

  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 5s
