apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: debezium-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 1
  {{- if .Values.debeziumConnect.version }}
  version: {{ .Values.debeziumConnect.version | quote }}
  {{- end }}
  bootstrapServers: kafka-cluster-kafka-bootstrap:9092
  {{- if .Values.debeziumConnect.image }}
  image: {{ .Values.debeziumConnect.image }}
  {{- end }}
  groupId: connect-cluster
  offsetStorageTopic: kafka_connect_offsets
  configStorageTopic: kafka_connect_configs
  statusStorageTopic: kafka_connect_status
  config:
    config.providers: secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  {{- if eq .Values.debeziumConnect.buildImage true }}
  build:
    output:
      type: docker
      image: {{ .Values.debeziumConnect.image }}
      pushSecret: docker-registry.secret
    plugins:
      - name: debezium-postgresql-connector
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.3.0.Final/debezium-connector-postgres-2.3.0.Final-plugin.tar.gz
  {{- else if .Values.debeziumConnect.usePluginImage }}
  plugins:
    - name: debezium-postgresql-connector
      artifacts:
        - type: image
          reference: {{ .Values.debeziumConnect.pluginImage }}
          pullPolicy: {{ .Values.debeziumConnect.pluginPullPolicy }}
  {{- end }}
