apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: debezium-connector-postgresql-product-db
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  config:
    database.hostname: postgresql.postgres.svc.cluster.local
    database.port: 5432
    database.user: ${secrets:postgresql.credentials:username}
    database.password: ${secrets:postgresql.credentials:password}
    topic.prefix: dbproduct
    database.dbname: product
    plugin.name: pgoutput
    slot.name: product_slot
    publication.name: product_publication
    publication.autocreate.mode: all_tables
    table.include.list: public.product
    schema.include.list: public
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter: org.apache.kafka.connect.json.JsonConverter
