write:
  replicas: 1
  initContainers:
<<<<<<< Updated upstream
    - name: init-loki-data
=======
    - name: loki-data-permissions
>>>>>>> Stashed changes
      image: busybox:1.36
      command:
        - sh
        - -c
<<<<<<< Updated upstream
        - mkdir -p /var/loki && chown -R 10001:10001 /var/loki
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
=======
        - chown -R 10001:10001 /var/loki && chmod -R u+rwX,g+rwX /var/loki
      securityContext:
        runAsUser: 0
>>>>>>> Stashed changes
      volumeMounts:
        - name: data
          mountPath: /var/loki
read:
  replicas: 1
backend:
  replicas: 1
  initContainers:
<<<<<<< Updated upstream
    - name: init-loki-data
=======
    - name: loki-data-permissions
>>>>>>> Stashed changes
      image: busybox:1.36
      command:
        - sh
        - -c
<<<<<<< Updated upstream
        - mkdir -p /var/loki && chown -R 10001:10001 /var/loki
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
=======
        - chown -R 10001:10001 /var/loki && chmod -R u+rwX,g+rwX /var/loki
      securityContext:
        runAsUser: 0
>>>>>>> Stashed changes
      volumeMounts:
        - name: data
          mountPath: /var/loki
loki:
  podSecurityContext:
    runAsNonRoot: false
  commonConfig:
    replication_factor: 1
  auth_enabled: false
<<<<<<< Updated upstream
  limits_config:
    ingestion_rate_mb: 64
    ingestion_burst_size_mb: 128
=======
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
>>>>>>> Stashed changes
test:
  enabled: false
storage:
  type: 'filesystem'
minio:
  enabled: true
  securityContext:
    enabled: true
    fsGroup: 0
    runAsGroup: 0
    runAsUser: 0

monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
