write:
  replicas: 1
  initContainers:
    - name: loki-data-permissions
      image: busybox:1.36
      command:
        - sh
        - -c
        - chown -R 10001:10001 /var/loki && chmod -R u+rwX,g+rwX /var/loki
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: data
          mountPath: /var/loki
read:
  replicas: 1
backend:
  replicas: 1
  initContainers:
    - name: loki-data-permissions
      image: busybox:1.36
      command:
        - sh
        - -c
        - chown -R 10001:10001 /var/loki && chmod -R u+rwX,g+rwX /var/loki
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: data
          mountPath: /var/loki
loki:
  podSecurityContext:
    runAsNonRoot: false
  commonConfig:
    replication_factor: 1
  auth_enabled: false
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
test:
  enabled: false
storage:
  type: "filesystem"
minio:
  enabled: true
  securityContext:
    enabled: true
    fsGroup: 0
    runAsGroup: 0
    runAsUser: 0

monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
