kafka:
  replicas: 1
  storeSize: 100Gi
zookeeper:
  replicas: 1
  storeSize: 5Gi
postgresql:
  username: yasadminuser
  password: admin
debeziumConnect:
  version: 4.2.0
  image: yas-debezium-connect-postgresql:1.0.1-kafka-4.2.0-debezium-3.3
  usePluginImage: false
  pluginImage: quay.io/debezium/connect:3.3
  pluginPullPolicy: IfNotPresent
  buildImage: false # Enabled only when pushing a custom Kafka Connect image to a registry.
