kafka:
  replicas: 1
  storeSize: 5Gi
zookeeper:
  replicas: 1
postgresql:
  username: yasadminuser
  password: admin
debeziumConnect:
  version: 4.3.0
  image: yas-debezium-connect-postgresql:1.0.1-kafka-4.3.0-debezium-3.3
  buildImage: false #Enabled when build debezium-connect-postgresql image
  usePluginImage: false
  pluginImage: quay.io/debezium/connect:3.3
  pluginPullPolicy: IfNotPresent
