opentelemetryCollectorConfig:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  processors:
    batch: {}

  exporters:
<<<<<<< Updated upstream
    debug:
      verbosity: detailed
    otlp_http:
=======
    otlphttp:
>>>>>>> Stashed changes
      endpoint: http://tempo:4318
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
<<<<<<< Updated upstream
        exporters: [otlp_http]
=======
        exporters: [otlphttp]
>>>>>>> Stashed changes
